### ISSUE TITLE
Issue with units of data

### ISSUE THREAD

**Issue by artur-amorim** [rcarcasses/HQCD-P#23]
Today we realized that the units of the of the cross-sections and their errors are not the same. Also from process to process the units of the observables change. So, we need to modify the code such that all the data is converted to GeV^(-4) (dsigma/dt) or GeV^(-2) (sigma) which are the units of the differential cross sections and cross sections respectively when computed in natural units.

**Comment by rcarcasses** [comment]
fixed in b3be77b0c7191cde0d9325ae3a677f0a4a9ae45e.
